import { StyleSheet } from "react-native";

export const colors = {
  bg: "#080d19",
  panel: "#111827",
  panel2: "#172033",
  border: "rgba(255,255,255,0.1)",
  text: "#f8fafc",
  muted: "#94a3b8",
  cyan: "#22d3ee",
  green: "#34d399",
  red: "#fb7185",
  amber: "#fbbf24",
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
    paddingTop: 18,
  },
  center: {
    flex: 1,
    justifyContent: "center",
    padding: 18,
  },
  header: {
    minHeight: 58,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerTitleWrap: {
    flex: 1,
    paddingRight: 10,
  },
  logo: {
    color: colors.text,
    fontSize: 21,
    fontWeight: "800",
  },
  title: {
    color: colors.text,
    fontSize: 22,
    fontWeight: "800",
  },
  subtitle: {
    color: colors.muted,
    marginTop: 2,
  },
  small: {
    color: colors.muted,
    fontSize: 12,
  },
  card: {
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.045)",
    padding: 16,
  },
  panel: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.panel,
    padding: 12,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  spread: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  input: {
    minHeight: 46,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: "#0f172a",
    color: colors.text,
    paddingHorizontal: 13,
  },
  inputGrow: {
    flex: 1,
  },
  multilineInput: {
    minHeight: 46,
    maxHeight: 110,
    paddingVertical: 12,
  },
  button: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: colors.cyan,
    paddingHorizontal: 14,
  },
  buttonText: {
    color: "#06111f",
    fontWeight: "800",
  },
  secondaryButton: {
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 12,
  },
  secondaryText: {
    color: colors.text,
    fontWeight: "700",
  },
  dangerButton: {
    backgroundColor: "rgba(251,113,133,0.16)",
  },
  dangerText: {
    color: colors.red,
    fontWeight: "800",
  },
  iconButton: {
    minWidth: 42,
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: 10,
  },
  iconText: {
    color: colors.text,
    fontWeight: "900",
    fontSize: 16,
  },
  disabled: {
    opacity: 0.45,
  },
  link: {
    color: colors.cyan,
    fontWeight: "800",
  },
  hint: {
    color: colors.cyan,
    fontSize: 12,
  },
  status: {
    color: "#a5f3fc",
    textAlign: "center",
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  list: {
    flex: 1,
  },
  scrollContent: {
    padding: 14,
    gap: 10,
  },
  chatItem: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.panel,
    padding: 12,
    gap: 6,
  },
  chatName: {
    color: colors.text,
    fontWeight: "800",
    fontSize: 16,
  },
  badge: {
    minWidth: 22,
    minHeight: 22,
    borderRadius: 11,
    backgroundColor: colors.cyan,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  badgeText: {
    color: "#06111f",
    fontWeight: "900",
    fontSize: 12,
  },
  onlineDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: colors.green,
  },
  messageList: {
    flex: 1,
    paddingHorizontal: 12,
  },
  messageContent: {
    paddingVertical: 12,
    gap: 8,
  },
  bubble: {
    maxWidth: "84%",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: colors.border,
  },
  bubbleMine: {
    alignSelf: "flex-end",
    backgroundColor: "rgba(34,211,238,0.16)",
  },
  bubbleTheirs: {
    alignSelf: "flex-start",
    backgroundColor: colors.panel,
  },
  bubbleSelected: {
    borderColor: colors.cyan,
  },
  bubbleText: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 21,
  },
  metaText: {
    color: colors.muted,
    fontSize: 11,
    marginTop: 4,
  },
  composer: {
    padding: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: 8,
  },
  actionBar: {
    gap: 8,
    padding: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: "#0b1220",
  },
  actionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  tabBar: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: "#0b1220",
  },
  tab: {
    flex: 1,
    minHeight: 54,
    alignItems: "center",
    justifyContent: "center",
  },
  tabActive: {
    backgroundColor: "rgba(34,211,238,0.12)",
  },
  tabText: {
    color: colors.muted,
    fontWeight: "700",
  },
  tabTextActive: {
    color: colors.cyan,
  },
  camera: {
    height: 320,
    overflow: "hidden",
    borderRadius: 14,
  },
  callOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
    backgroundColor: "#020617",
  },
  remoteVideo: {
    flex: 1,
    backgroundColor: "#020617",
  },
  localVideo: {
    position: "absolute",
    right: 16,
    top: 82,
    width: 112,
    height: 150,
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: colors.border,
  },
  callTop: {
    position: "absolute",
    top: 42,
    left: 16,
    right: 16,
    zIndex: 2,
  },
  callCenter: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  callAvatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(34,211,238,0.14)",
    borderWidth: 1,
    borderColor: "rgba(34,211,238,0.35)",
  },
  callAvatarText: {
    color: colors.cyan,
    fontSize: 34,
    fontWeight: "900",
  },
  callControls: {
    position: "absolute",
    bottom: 34,
    left: 16,
    right: 16,
    flexDirection: "row",
    justifyContent: "center",
    gap: 10,
    zIndex: 2,
  },
  callControl: {
    minWidth: 58,
    height: 52,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  callControlActive: {
    backgroundColor: "rgba(34,211,238,0.22)",
  },
  callEnd: {
    backgroundColor: colors.red,
  },
  callControlText: {
    color: colors.text,
    fontWeight: "900",
  },
});
